# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e16891cd424ba0368ea4051c042380306f36548b9857da28275267447680a2ccbcbd0d01167a9a941351025d5b643e4b2da5cbe9f1e55ba40a24efbe9e2a66c1

test:
  secret_key_base: d8aeb0accf5a567c159dc17b3be611f2316f5b42d9cf61311765406008652bc09290263bef579833edbb8dbc8f0c29bf2063aeed93f0b1c71a8baf29dca7c947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
